### ISSUE TITLE
Alert about Country Code

### ISSUE THREAD

**Issue by MarcooRo** [flydev-fr/PaymentStripeElements#1]
I get an error about the country code, the letters are in lowercase, the console log ask me to use uppercase.
I try to change that string at row 34:  
From `$this->country = strtolower($this->defaultCountry)` to `$this->country = strtoupper($this->defaultCountry)`
The error from the console log is gone.

But I saw that it doesn't automatically take the value of the Padpoller field, how can I use the data present in pad_countrycode?

**Comment by flydev-fr** [comment]
Thanks @MarcooRo 

Effectively I made a mistake - the country code was hardcoded before. Checking for pad_countrycode right now.

**Comment by flydev-fr** [comment]
@MarcooRo  I just pushed an update, Stripe should not complain anymore. I am checking for pad_country field.

**Comment by flydev-fr** [comment]
@MarcooRo pad_countrycode refere to the customer country code. In the module, the country field, refere to the country Stripe's account.

Hope you get it.

https://stripe.com/docs/js/payment_request/create

```
country / REQUIRED / string
The two-letter country code of your Stripe account (e.g., US).
```

**Comment by MarcooRo** [comment]
Ok, all clear, that's right. Thank you so much
