### ISSUE TITLE
Redirect the user to the pagans of thanks.

### ISSUE THREAD

**Issue by MarcooRo** [flydev-fr/PaymentStripeElements#2]
After the payment I can't redirect the user to the thank-you page, the link that is generated has only the order number inside but not the url I entered in the field successUrl

On line 212 I see the writing:
`window.location.href = "'. $ successUrl.'? o = '. $ this-> id.'"`

It looks like this must go. maybe the problem is on line 102:
`$ successUrl = $ this-> user-> language! == wire ('languages') -> get ('default')? $ this-> get ('successUrl __'. $ this-> user-> language-> id): $ this-> get ('successUrl'). '/';`

How should I write the URL in the backend? all the URL or just a part? 
I try both: the full URL and the  /checkout/success/ but they seem not to work.

**Comment by flydev-fr** [comment]
It works as intended. 

- Allow URL Segments on the checkout template.
- Fill all the urls needed in the module config

**Comment by flydev-fr** [comment]
You should put as URL something like that (you do not need to create a new page) :  https://myawesomeshop.com/notification

[thread on ProcessWire.com/talk](https://processwire.com/talk/topic/24737-module-payment-stripe-module-sca-ready-for-processwire/?do=findComment&comment=208662)
